### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by msvbg** [lelongg/geo-clipper#20]
Hey! Thanks for this crate, it works really well. It's missing a license though. Is it it fair to assume that it's ISC licensed like clipper-sys? Some of your other crates like geo-offset and geo-visibility also look neat and are missing licenses too.

**Comment by lelongg** [comment]
Indeed, I did not add a LICENSE.txt. Will do but in the meantime you can find the license in the Cargo.toml

Beware that this crate makes use of Clipper which is licensed separately
