### ISSUE TITLE
Polygon union without interiors

### ISSUE THREAD

**Issue by flaport** [lelongg/geo-clipper#21]
Hi!

Is there a way to get the result of a polygon union without any interiors?

Something like this?

![image](https://user-images.githubusercontent.com/15832886/186269304-0e1a1ca2-13cd-4918-ae19-50640fcf2677.png)

This would be really useful for GDSII processing (the GDSII format does not support any holes).

**Comment by lelongg** [comment]
Hi,

I don't believe clipper support that. Let me know if you find a way with [clipper](https://angusj.com/delphi/clipper/documentation/Docs/Overview/_Body.htm)
