### ISSUE TITLE
Clipper Version

### ISSUE THREAD

**Issue by kurt-rhee** [lelongg/geo-clipper#25]
Hello,

I just have a question, does this algorithm implement clipper1 or clipper2?

**Comment by lelongg** [comment]
Hello,

Its clipper 1, clipper 2 support PR welcome !

**Comment by tirithen** [comment]
@kurt-rhee in case clipper2 is still interesting for you I have published a safe https://crates.io/crates/clipper2 crate and an unsafe https://crates.io/crates/clipper2c-sys crate. They currently provide the major parts of the API for version 1.4.0 of Clipper2 via FFI.

Maybe those could be of help for you? Maybe they could also be useful for the geo-clipper crate as well in one way or the other.

**Comment by kurt-rhee** [comment]
Wow @tirithen thank you very much!
